services:
  db:
    image: postgres:16
    container_name: postgres_credito_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network
  
  create-topics:
    image: confluentinc/cp-kafka:7.4.0
    container_name: create_topics
    depends_on:
      - kafka
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 20
        kafka-topics --create --topic credit-events --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092
    restart: "no"
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - app-network

  credito-api:
    build:
      context: ./credito-api
      dockerfile: Dockerfile
    container_name: credito-api
    depends_on:
      - db
      - kafka
      - zookeeper
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_SCHEMA: public
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
    networks:
      - app-network

  credito-front:
    build:
      context: ./credito-front
      dockerfile: Dockerfile
    container_name: credito-front
    ports:
      - "4200:4200" 
    depends_on:
      - credito-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
